### ISSUE TITLE
ToDo list until MVP

### ISSUE THREAD

**Issue by cmsato09** [cmsato09/DQMonstersDB-streamlit#4]
- [X] Close pull request #1  and merge. Create new branch for next stuff.
- [X] Create separate class w/ API endpoints and helper functions --> created new py file, just need to refactor it.
- [X] Host FastAPI so we don't have to run it locally anymore --> now hosted on Deta
- [x] reorganize skills table w/ pandas --> make it pretty
- [x] add query filters for monster list, items table, and skills table
- [x] create static file for images in FastAPI or go the direct route and figure out where to host them.
- [x] Refactor some of the FastAPI files --> need to add one last endpoint related to the breeding table.
